### ISSUE TITLE
heatmap value

### ISSUE THREAD

**Issue by BioEpi** [open2c/coolpuppy#100]
Hello, woud you like to explain what the values printed in the heatmap mean?

<img width="119" alt="image" src="https://user-images.githubusercontent.com/12387462/192849131-70a73ee6-3073-4b5f-b943-ce1e0959a373.png">
<img width="152" alt="image" src="https://user-images.githubusercontent.com/12387462/192849174-ed1515e6-adf5-4215-98ae-a640662e93b6.png">

**Comment by Phlya** [comment]
Hi, this value indicates a "score" for the pileup. It tries to choose in a smart way to calculate the appropriate metric.

If the pileup is not local, it calculates the average values of the central 3x3 square of the pileup.

If the pileup is local but not rescaled (your first example) it calculates the average values of the top left and bottom right squares, and divides by average of top right and bottom left, while ignoring the central 3 rows and columns (thus it measures insulation strength).

If the pileup is local and rescaled (your second example), it will measure "domain strength", it will divide sum of values in a square from the central part of a matrix by the top and right rectangles, i.e. interactions within the domain vs interactions of the domain with the nearby regions.

**Comment by Phlya** [comment]
Hope this is helpful, feel free to ask for more details.

**Comment by BioEpi** [comment]
thanks.
