### ISSUE TITLE
how to plot difference

### ISSUE THREAD

**Issue by BioEpi** [open2c/coolpuppy#102]
Hello,
    plotpuppy can plot individual plots, I am just wondering whether plotpuppy can plot the difference of pile up contact frequencies.

**Comment by Phlya** [comment]
Check out this section of the tutorials, hope it helps
https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_API.html#dividing-pileups
https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html#dividing-pileups

**Comment by Phlya** [comment]
Did this help?

**Comment by Phlya** [comment]
Try making two pileups for the two conditions, and then using the `dividepups.py` command to generate a ratio of the two pileups, and see if it works how you expect.

**Comment by BioEpi** [comment]
yes, thanks.

**Comment by Phlya** [comment]
Great!
