### ISSUE TITLE
Install error: module 'coolpuppy.lib'

### ISSUE THREAD

**Issue by OdysseyXD** [open2c/coolpuppy#104]
Hi,
I just met totally the same installation error as in #97. I've tried aforementioned command:
`python3 -m pip install --force-reinstall --upgrade --no-cache-dir --no-deps https://github.com/open2c/coolpuppy/archive/refs/heads/master.zip` 
not working.

It prompt:
Successfully installed coolpuppy-1.0.0.dev0

After `coolpup.py` :
Traceback (most recent call last):
  File ".conda/envs/cool/bin/coolpup.py", line 5, in <module>
    from coolpuppy.CLI import main
  File ".conda/envs/cool/lib/python3.7/site-packages/coolpuppy/CLI.py", line 2, in <module>
    from .coolpup import pileup
  File ".conda/envs/cool/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 27, in <module>
    from .lib import numutils
ModuleNotFoundError: No module named 'coolpuppy.lib'

**Comment by efriman** [comment]
It seems like the new version hasn't installed correctly. There should be a folder "lib" in your coolpuppy/coolpuppy folder, in your case .conda/envs/cool/lib/python3.7/site-packages/coolpuppy/lib I think. You may try to uninstall it and reinstall from scratch or install it in a new environment.

**Comment by Phlya** [comment]
Probably the latest commit from https://github.com/open2c/coolpuppy/pull/108 should solve this issue!
