### ISSUE TITLE
Resolution compatibility between .cool file and .bedpe file for pile-ups of predefined regions pairs

### ISSUE THREAD

**Issue by Soh-hyon** [open2c/coolpuppy#107]
Hi, I'm Soh-hyon:)

I'm trying to average predefined 2D regions corresponding to specific loops.
I generated 1kb-resolution .cool file using **Cooler** and .bedpe file using **FitHiChIP**. When using FitHiChIP, I set binsize as 5 kb. (Actually, there was no significant loop in smaller bin size.)

Does the resolution of .cool file and .bedpe have to be the same?

**Comment by Phlya** [comment]
No Soh-hyon - no, that doesn't matter.
