### ISSUE TITLE
ValueError: Can't make by-window pileups without making combinations

### ISSUE THREAD

**Issue by sabrsyed** [open2c/coolpuppy#11]
Hi, I was interested in getting pile-up data at all looping interactions that are in my double-bed file so was trying to use the --by-window option, but have encountered the following error:

ValueError: Can't make by-window pileups without making combinations

Here's what I ran: 
coolpup.py experiment_mm10.1000.cool loopPrediction_p0.7.bed --nshifts 10 --unbalanced --coverage_norm --mindist 100000 --outname loopPileup_bywindow.txt --by_window --log WARNING

I'm not sure I understand the error, so any help would be much appreciated. Thanks

**Comment by sabrsyed** [comment]
--by_window   Create a pile-up for each coordinate in the baselist.
                        Will save a master-table with coordinates, their
                        enrichments and cornerCV, which is reflective of
                        noisiness (default: False)

I thought this description could be applied to bedpe but I guess not. Thanks for clarifying!

**Comment by Phlya** [comment]
Sorry, I should explain it better then! Will keep it open for now as a reminder to clarify the description.

**Comment by Phlya** [comment]
I added an explicit comment about this to the docstring, hope it helps.
