### ISSUE TITLE
No chromosomes are in common

### ISSUE THREAD

**Issue by Jason-Qiuhai** [open2c/coolpuppy#110]
Hi,

I had clr chromnames as
![0D3D98D9-03C6-4386-9ADB-3648D504F66C](https://user-images.githubusercontent.com/71804132/197368894-1f70f97e-e16c-4d03-81dc-f3c7c39a88a0.png)

and stripe dataframe 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/71804132/197397337-7c46dd30-c325-4b61-8e83-c4f7366d0706.png">

When I ran 
pup = coolpup.pileup(clr, stripes, features_format='bedpe', local=True, rescale=True, clr_weight_name=False)

I got the error message 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/71804132/197368922-a948a59e-9ed2-4bce-9d47-7b94ef541f11.png">

I got confused why I got the error.

**Comment by Phlya** [comment]
The error is indeed confusing, but can you try running it with local=False? You can't really use bedpe data for local pileups...

**Comment by Jason-Qiuhai** [comment]
> 

Thanks for the quick reply. I tried running it with local=False, but got the same error message. I checked the source code. If I changed the 934 line code 'self.CC.final_chroms' into 'self.CC.chroms', it might help. I still got warning messages saying 'No regions in features (maybe all below mindist?)'.

**Comment by Phlya** [comment]
Ah yes, that's a good hint - your features are indeed all very close to the main diagonal, so you need to set mindist=0.

**Comment by Jason-Qiuhai** [comment]
> Ah yes, that's a good hint - your features are indeed all very close to the main diagonal, so you need to set mindist=0.

Thanks so much for the instant reply. I set mindist=0 and successfully ran the code. However, I did not get any meaningful output. I summarized my questions as follows.

1. I want to do pileup plot for stripes, which are lines extending from the diagonal. Is my stripe location format correct as input for coolpup?
<img width="454" alt="image" src="https://user-images.githubusercontent.com/71804132/197397035-1fdfb894-5f28-44f3-88aa-7752c44bcde9.png">

2. Is my code running coolpup.pileup correct?
<img width="950" alt="image" src="https://user-images.githubusercontent.com/71804132/197397108-39f82017-a3df-4a9d-8330-53c3b85054e5.png">

3. My aim is to create a plot like this (copied from stripenn paper, in which they said 'pileup plot of all stripes detected by each method was generated using coolpup.py program where ‘--local –rescale --unbalanced’ options were used.')
<img width="431" alt="image" src="https://user-images.githubusercontent.com/71804132/197397164-0862863c-33a8-4ee5-8262-d1d86702856a.png">

I don't know how to run the coopup.py file in my command line. I tried to run it but got errors
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/71804132/197397261-47191075-f88e-4f83-adc3-479364a767c6.png">

I really appreciate any suggestions.

**Comment by Phlya** [comment]
Have you installed the package? Or did you just download the code? You need to run `pip install https://github.com/open2c/coolpuppy/archive/master.zip`, then you should have a `coolpup.py` command available in your terminal.

For the stripenn paper, this description is really not enough. As you experienced, just running coolpup.py with the stripe annotation directly with those arguments won't work at all. From the plot it looks like perhaps they preprocessed the stripe annotation and were looking at pairs of neighbouring stripes?

**Comment by Jason-Qiuhai** [comment]
> Have you installed the package? Or did you just download the code? You need to run `pip install https://github.com/open2c/coolpuppy/archive/master.zip`, then you should have a `coolpup.py` command available in your terminal.
> 
> For the stripenn paper, this description is really not enough. As you experienced, just running coolpup.py with the stripe annotation directly with those arguments won't work at all. From the plot it looks like perhaps they preprocessed the stripe annotation and were looking at pairs of neighbouring stripes?

Thanks very much. I will take a try.

**Comment by Jason-Qiuhai** [comment]
> Have you installed the package? Or did you just download the code? You need to run `pip install https://github.com/open2c/coolpuppy/archive/master.zip`, then you should have a `coolpup.py` command available in your terminal.
> 
> For the stripenn paper, this description is really not enough. As you experienced, just running coolpup.py with the stripe annotation directly with those arguments won't work at all. From the plot it looks like perhaps they preprocessed the stripe annotation and were looking at pairs of neighbouring stripes?

Hi Phyla,

My data looks like this
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/71804132/197917129-1059e9b4-c2a5-4559-b129-84aa0821cef6.png">

When I run the code 
coolpup.py --features_format bedpe 4DNFI2TK7L2F.cool result_filtered.bedpe.tsv

I got the error message
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/71804132/197917091-0b98ff3e-7f52-45f3-989e-5439e2f285b1.png">

Is my code correct? I want to get the pileup plot for my stripe regions.

**Comment by Phlya** [comment]
You need to either balance your cooler, or give an argument `--clr-weight-name` to not use balanced data.

**Comment by Phlya** [comment]
I assume this is solved, feel free to reopen!
