### ISSUE TITLE
how to plot short and long contact frequency

### ISSUE THREAD

**Issue by BenxiaHu** [open2c/coolpuppy#111]
Hello, 
    I was just wondering whether coolpup.py can make the APA for short and long range contact frequncy. please see the following picture.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/12387462/197814045-ceca7b61-b032-46a9-9b47-f2444a493f0e.png">

 would you like to explain what the [--mindist MINDIST] [--maxdist MAXDIST] are? Are both compatible with [--flank FLANK] ?
Best,

**Comment by BioEpi** [comment]
> See here https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html#by-distance-pileups

thanks.
Why does that command output too many columns for each group?
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/12387462/197818470-fad16ea6-1def-4bc0-9f3d-7db5e23d9e34.png">

**Comment by BioEpi** [comment]
> Yes, you can simply use --by-distance argument for this!
> 
> Or indeed run the same command a few times separately with different --mindist --maxdist arguments, in base pairs. They are completely independent of --flank.

for short range, –by_distance 1000000 2000000 should work. 
long range: what I want to plot is from 3Mb to the maximum distance (I do not know the actual number)

**Comment by Phlya** [comment]
The command in the tutorial also splits by strand, so it creates a lot of pileups at the same time. You don't need that in this case.

You can choose any distances you want, you can do smth like –by_distance 1000000 2000000 100000000 to go up to 300 Mb, that would for sure cover everything (in "normal" mammalian genomes). Just give ti a number longer than the longest chromosome, basically.

**Comment by Phlya** [comment]
Assuming this is clear, feel free to reopen!
