### ISSUE TITLE
how to plot interchromosome interactions

### ISSUE THREAD

**Issue by BioEpi** [open2c/coolpuppy#113]
Hello, 
I was just wondering how to plot APA for interchromosome interactions?
I just used the --trans and --expected test_expected_trans.tsv.
do you think what i did was correct?

**Comment by Phlya** [comment]
Yes, sounds correct!

**Comment by Phlya** [comment]
Here is the section in the tutorial about it FYI, hope it helped!
https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html#trans-inter-chromosomal-pileups
