### ISSUE TITLE
[Q]Error in Apa 

### ISSUE THREAD

**Issue by ag-abhishek** [open2c/coolpuppy#123]
Hi, 

I am using Pile-ups of predefined region pairs, but I am facing an error while using the command. Here I am attaching the screenshot from the error. 
Please help me resolve the issue.
![image](https://user-images.githubusercontent.com/74924384/215343683-c524ad68-c610-4e39-853f-90953d4f824f.png)

**Comment by Phlya** [comment]
Looks like maybe a problem with the sklearn installation... I'm not sure how to help, try creating a new conda environment with coolpuppy.

**Comment by Phlya** [comment]
Assuming this is resolved, feel free to reopen.
