### ISSUE TITLE
[Q]When the new version performs rescaling pileup analysis, there is a problem with the ignore_diags parameter

### ISSUE THREAD

**Issue by WANGchuang715** [open2c/coolpuppy#124]
I noticed that when the new version performs rescaling pileup analysis, the same ignore_diags parameter presents different results, and the new version does not go to the masked diagonal area.However, the new version of On-diagonal pileup analysis does not have this problem.
![A1 TAD domains pileup (16)](https://user-images.githubusercontent.com/67625036/217697381-517705dd-5cd1-4a3f-9874-857f25f259ef.png)
![A1 TAD domains pileup (17)](https://user-images.githubusercontent.com/67625036/217697467-a18d5f16-ed48-45c6-930b-d1f08d5
![A1 TAD boundary pileup (4)](https://user-images.githubusercontent.com/67625036/217697906-a92388fe-0378-448c-9c2a-83546d688054.png)
44b25.png)

I'm not sure if it will have an effect on the result, because I need to calculate domain_score, or do you have any suggestion for ignore_diags parameter?

**Comment by Phlya** [comment]
Could you please clarify exactly what you did, what you expected and what the problem is?

**Comment by WANGchuang715** [comment]
> I think I found out what the issue was and it should be fixed. Please try again after updating using the latest github version
Thank you for your modification, the display is now normal, and the domain_score has also changed.
![image](https://user-images.githubusercontent.com/67625036/218047067-8122853d-5e4e-4845-9c82-8912f2e29c75.png)
 Different ignore_diags parameters will produce different scores, do you have any suggestions for this parameter setting?

**Comment by Phlya** [comment]
Great to hear! Thank you for fixing this @efriman 

In general in most cases ignore_diags=2 is a good choice. But sometimes it's a little data dependent, in particular for rescaling.

**Comment by WANGchuang715** [comment]
> Great to hear! Thank you for fixing this @efriman
> 
> In general in most cases ignore_diags=2 is a good choice. But sometimes it's a little data dependent, in particular for rescaling.

Thanks for your advice.
