### ISSUE TITLE
Load/reoder chromosomes

### ISSUE THREAD

**Issue by odovgusha** [open2c/coolpuppy#131]
Hi, could you suggest a way to reorder the chromosomes in the cooler or load only particular chromosomes from the .cool file? 
I wanted to save RAM and try my script on some toy dataset. However, it seems that I cannot just plot some (present in the bed file) of the chromosomes from the cool file.

Many thanks!

**Comment by Phlya** [comment]
Sorry for the late reply. Hopefully you solved your problem by now, and in the future it a better place for questions like this is the cooler or cooltools repository.

In case you still need to reorder chromosomes in a cooler, I actually recently wrote a tool for that, which is currently in a PR in cooltools: https://github.com/open2c/cooltools/pull/448 You can install the version from that branch of cooltools and use it.
