### ISSUE TITLE
About plotpup.py error

### ISSUE THREAD

**Issue by GleeenSIBS** [open2c/coolpuppy#133]
When I use plotpup.py to perform the local pileups, I get the following error:
AttributeError: 'DataFrame' object has no attribute 'iteritems'

My command is "coolpup.py test.cool TAD_domain.bed --rescale --local --rescale_size 99 --rescale_pad 1 --n_proc 50  --features_format bed --expected test_expected_cis.tsv --outname test_pileup.txt
plotpup.py --not_symmetric --cmap coolwarm --scale log --vmin 0.5 --vmax 2 --dpi 300 --height 5 --output test_ATA.pdf --input_pups test_pileup.txt"

The version is 1.0.0. Could you help me? Thanks!

**Comment by Phlya** [comment]
Please try downgrading pandas to any version <2.0

**Comment by GleeenSIBS** [comment]
> Please try downgrading pandas to any version <2.0

Thanks! I downgraded pandas to version 1.5.3 and reinstalled coolpuppy version 1.0.0 , it worked!
However, I want to use the matrix from coolpup.py output, I can't plot heatmap using R. So, how I can get the available matrix format which can be reanalysed to plot heatmap by other tools. Thanks !

**Comment by Phlya** [comment]
The output is an HDF5 file, you can use R packages for reading HDF5 to load it. Can't help you much with that though, sorry, I don't use R. Feel free to get in touch if the structure of the file is unclear, I hope it is...

**Comment by GleeenSIBS** [comment]
Thanks a lot!

**Comment by GleeenSIBS** [comment]
Thanks a lot !

**Comment by Phlya** [comment]
Assuming this is resolved, feel free to reopen.
