### ISSUE TITLE
[Q]ValueError: Too few columns

### ISSUE THREAD

**Issue by jiangshan529** [open2c/coolpuppy#134]
Hi, dear authors of coolpup,

I am using coolpup to draw a local pileup of a bed file(three columns seperated by tab). However, it reports the error"ValueError: Too few columns". How should I deal with that? The version of coolpup is 1.1.0. The full error message is as below:

coolpup.py WT_merge_5k.cool aa.bed1 --outname cc4.txt --flank 250000 --local --n_proc 16 --clr_weight_name ""
/home/unix/bai/.conda/envs/coolpuppy/lib/python3.9/site-packages/cooltools/lib/numutils.py:652: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_symmetric(
/home/unix/bai/.conda/envs/coolpuppy/lib/python3.9/site-packages/cooltools/lib/numutils.py:727: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_asymmetric(x, max_iter=1000, tol=1e-5, verbose=False):
Traceback (most recent call last):
  File "/home/unix/bai/.conda/envs/coolpuppy/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/unix/bai/.conda/envs/coolpuppy/lib/python3.9/site-packages/coolpuppy/CLI.py", line 434, in main
    raise ValueError("Too few columns")
ValueError: Too few columns

**Comment by Phlya** [comment]
Try specifying `--features-format bed`
Or you can rename the file, so that extension is `.bed`.

**Comment by Phlya** [comment]
I assume this is fixed, feel free to reopen.
