### ISSUE TITLE
how  to generate the expected.tsv?[Q]

### ISSUE THREAD

**Issue by JiaoLaboratory** [open2c/coolpuppy#136]
**State the question**
A clear and concise description of the question.

**What have you tried?**
- [ ] Have you read the documentation and tutorials about your question?

**Additional context**
 
Dear coolpuppy developer,
thank you for you tool, that is so good,
I want to to know how  can i generate the background file (expected.tsv) using coolpuppy ?

**Comment by Phlya** [comment]
Please see the tutorials. E.g. here for Python API: https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_API.html#pileups-of-observed-over-expected-interactions and here for CLI: https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html#chromosome-arm-wide-expected-normalization
