### ISSUE TITLE
Can coolpuppy use raw cool file to perform analysis?

### ISSUE THREAD

**Issue by JiaoLaboratory** [open2c/coolpuppy#138]
**State the question**
A clear and concise description of the question.

**What have you tried?**
- [ ] Have you read the documentation and tutorials about your question?

**Additional context**

Hi, thanks for your coolpuppy,

I use "coolpup.py  flower_vs_leaf.cool  test.bed -p 30 -o out.clpy --rescale --local --ignore_diags 0  --rescale_flank 0.5" to perform my analysis, while I met "
ValueError: No column 'bins/weight'found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False ";

I want to know how can I set "balance=False",  It seems no such option in  coolpuppy. 
Also, in fact I don't want to normolize my hic data, Can coolpuppy use raw cool file to perform analysis?
thank you very much!!

**Comment by efriman** [comment]
Hi, 

Yes, using `--clr_weight_name ""` in the CLI or `clr_weight_name=None` in the API

https://github.com/open2c/coolpuppy/blob/bba97ac6a2f1a298c617010b5c11531b922cb5c4/coolpuppy/CLI.py#L284

Elias

**Comment by JiaoLaboratory** [comment]
Yes, great, I have run coolpuppy successfully, and did many alalysises use coolpuppy , It really nice!!!
I have a new question, may be out of coolpuppy.
In fact I have two hic data, from tissue1 and tissue2.  And I want to compare the two data and get a tissue1_vs_tissue2.cool for further analysis.  Could you give me some advice on how to generate such file and futher be supported by coolpuppy?

**Comment by Phlya** [comment]
Glad it now worked well for you!
