### ISSUE TITLE
dividepups.py error

### ISSUE THREAD

**Issue by BenxiaHu** [open2c/coolpuppy#140]
Hello,
   I used dividepups.py to divide two pileups generated by plotpup.py. However, I got this error:
AssertionError: Cannot divide these pups, cooler is different between them.

dividepups.py case_coolpuppy ctrl_coolpuppy -o result.pdf

**Comment by efriman** [comment]
Hi BenxiaHu, 

Can you please try this with the latest github version? This was fixed some time ago. 

Elias

**Comment by BenxiaHu** [comment]
yes, it works. thanks.
