### ISSUE TITLE
[Q]How to get the matrix data after running coolpup.py

### ISSUE THREAD

**Issue by valderpan** [open2c/coolpuppy#141]
Hi, I ran the following command:
`coolpup.py WT_20000.iced.cool WT.mm10_allchr.20kb.TAD.bed --expected mm10_KO_expected_cis.tsv --rescale --local -p 10`

I want to plot a plot like the one below :
![example_local_rescaled_pileup](https://github.com/open2c/coolpuppy/assets/51531508/266e9cd3-6e89-43da-85bf-e26565d5f421)

After running this command I get a `clpy` file, when I try to check it I'm told it's a binary file that can't be viewed.

I want to customize the plot based on the generated file, even though the `clpy` can be plotted via `plotpup.py`

Can you tell me how to get the matrix file for the plot or is there any way to convert the `clpy` to an `np.txt `file (like [the txt](https://github.com/Phlya/coolpuppy_paper/blob/master/local/pileups/Auxin.mm9.mapq_30.1000-25.0K_over_boundaries_Bonev_ES.mm9.mapq_30.1000.mcool_25000_IS1000000_minBS_0.1_1-shifts_local.np.txt) file mentioned by paper)?

**Comment by Phlya** [comment]
Are you familiar with Python at least a little bit?
Sorry about the format change, but now the files store a lot of metadata that is difficult to keep in a text file...

**Comment by valderpan** [comment]
Thank you for your quick reply.
I don't know much about plotting with matplotlib, so I want to get the raw data to do it through R.

**Comment by Phlya** [comment]
Did you close the issue because you figured it out?
