### ISSUE TITLE
Y-Axis labels missing with plotpup.plot

### ISSUE THREAD

**Issue by linus3210** [open2c/coolpuppy#142]
Hi, 

`plotpup.plot` in the python API is currently not displaying the labels on the Y-axis despite the `plot_ticks` option being enabled. The axis labels are currently only displayed on the X-axis. 

![pup_tandem_plot](https://github.com/open2c/coolpuppy/assets/165179709/e577a15e-f48a-41d9-8e4b-56d972241111)

I'm using the latest version of `coolpup.py` in Jupyter notebooks running on WSL Ubuntu with python version 3.10.3.

**Comment by efriman** [comment]
Hi @linus3210. This is not actually a bug but intended behaviour to avoid clutter, as the pileup is always symmetric so the x and y axis labels are the same. You can plot the matrix, which is in the "data" column, yourself using e.g. matplotlib and customise it as you wish.
