### ISSUE TITLE
[Q]loop analysis takes long time

### ISSUE THREAD

**Issue by jiangshan529** [open2c/coolpuppy#149]
Hi. I am ploting hic file on a bedpe file.  the bedpe is tab seperated and has six columns, and it contains 2815 rows in total,

however, when I run a pileup on those loops it takes long time and it reported below messages, it seems most chromosome has more contact than my bedpe file of all chromosomes in total. Is this correct? Thanks!
INFO:coolpuppy:('13', '13'): 215
INFO:coolpuppy:('4', '4'): 1621
INFO:coolpuppy:('8', '8'): 2182
INFO:coolpuppy:('9', '9'): 3882
INFO:coolpuppy:('18', '18'): 175
INFO:coolpuppy:('14', '14'): 4157
INFO:coolpuppy:('15', '15'): 5161

**Comment by Phlya** [comment]
What command do you run?

**Comment by jiangshan529** [comment]
> What command do you run?

coolpup.py aa_5k.cool group_none.bed --outname none.txt --flank 250000 --n_proc 16 --clr_weight_name ""
plotpup.py --input_pups none.txt --not_symmetric  --output none.pdf

**Comment by Phlya** [comment]
Try adding `--features_format bedpe`
Your file ends with .bed, so coolpup.py assumes it's a .bed file, not .bedpe, so it calculates pairwise combinations of all left sides of the loops.

Also, the output is not in .txt format, just FYI...

**Comment by jiangshan529** [comment]
thank you!

**Comment by Phlya** [comment]
I assume this is fixed then?

**Comment by jiangshan529** [comment]
yes, thank you!
