### ISSUE TITLE
 No chromosomes are in common between the coordinate file and the cooler file. 

### ISSUE THREAD

**Issue by ratheraarif** [open2c/coolpuppy#151]
Thank you for  making such wonderful tool.

when I try to execute the following code 
`pup = coolpup.pileup(clr_MT, cenI_vs_all, features_format='bedpe', local = False,
                        flank=flank, min_diag=0)`

ValueError: No chromosomes are in common between the coordinate
                   file and the cooler file. Are they in the same
                   format, e.g. starting with "chr"?
                   
please note that the chromosome names are however same

`> clr_MT.chromnames` gives 
['chrI',
 'chrII',
 'chrIII',
 'chrIV',
 'chrV',
 'chrVI',
 'chrVII',
 'chrVIII',
 'chrIX',
 'chrX',
 'chrXI',
 'chrXII',
 'chrXIII',
 'chrXIV',
 'chrXV',
 'chrXVI',
 'chrM']

and the cenI_vs_all looks like 
<img width="450" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/96f3d60d-6f06-4d4e-bc3e-89666ab44327">

`cooltools.__version__` is '0.7.0'
`bioframe.__version__` is 0.4.1

I also tried with `local= True` but it still does not work.

please note that I am actually interested in doing pileup of how centromere of chr1 interacts with all other centromeres.

  
I also tried the same in cooltools with 
`stack_WT = cooltools.pileup(clr_WT, cenI_vs_all, view_df=chr_arms, expected_df=expected_WT, flank=flank)
mtx_WT = np.nanmean(stack_WT, axis=0)`
 it generates a matrix of all `Nans`

**Comment by efriman** [comment]
Hi. If you want to do cross-chromosomal you have to specify trans=True. Please see tutorial https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_API.html#trans-inter-chromosomal-pileups

**Comment by ratheraarif** [comment]
Thank you for the quick reply. I tried to run the following code 
`pup = coolpup.pileup(clr_MT, pairs, features_format='bedpe',
                     expected_df=trans_expected_MT, trans=True, flank = 5000,
                     rescale=True, rescale_flank=1, rescale_size=99)`
and plotted the output as 

`fg = plotpup.plot(pup,
                  score=True, cmap='coolwarm', scale='log', 
                  sym=True, vmax=100, height=3)`
and the plot is shown as 

<img width="316" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/f65281b8-2a93-4801-8443-e5a8821c1a77">

However, I expect the plot to look like this

<img width="204" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/ea0ceb2f-f7f6-4ced-aa49-ce08b94f8e20">

This plot shows the average interaction of centromere centromere interaction. Am I missing anything here

**Comment by efriman** [comment]
Can you try it with rescale=False

**Comment by ratheraarif** [comment]
setting rescale =False seems to work but not as expected. the output now looks like:

<img width="316" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/1c2171f0-986b-432e-87da-2fadf13e9952">

please note that I ran the following code:

`trans_expected_MT = expected_trans(
    clr_MT,  
    chunksize=1000000)
`

`pup_MT = coolpup.pileup(clr_MT,  pairs, features_format='bedpe',
                  trans=True, expected_df=trans_expected, flank = 10000,
                     rescale=False)`

`fg = plotpup.plot(pup_MT,
                  score=True, cmap='coolwarm', scale='log', 
                  sym=True, vmin = 100, height=2)
`

Do I need to change any additional settings.

**Comment by Phlya** [comment]
Are you sure flank=10000 is reasonable? The whole pileup is enriched, relative to expected, so perhaps you need a much larger flank to see it as a spot?

**Comment by ratheraarif** [comment]
Oh sorry, actually the flank should be 50000 and it's working as expected now.

But I have one more question. I have  `pup_WT` and `pup_MT` and I want to make differential out of it i.e., `pup_WT/pup_MT`.  Can you please help out how to do that?

**Comment by ratheraarif** [comment]
Oh I see. The I needed to increase the flank size and it's working as expected. Thank you!

**Comment by ratheraarif** [comment]
I was wondering if it's possible to know the contribution of each pileup to the final plot. I want to find out how each centro centro interaction( for instance chrI  with all other, chrII with all other and the like) contributed to the final enrichment and plot that as a histogram. In my opinion I should have 16 different matrices on for each chromosome, so it should be possible. Similar to what is shown here( https://coolpuppy.readthedocs.io/en/latest/Examples/TAD_score.html)

**Comment by efriman** [comment]
You can do `groupby=["chrom1", "chrom2"]` and then plot with cols and rows if you want per chromosome plots. If you want numbers, you'll have to extract the values from the pileup object, e.g. if you want to take the mean of the center.

**Comment by ratheraarif** [comment]
thank you! will give it a try
