### ISSUE TITLE
[BUG]Labels messed up in plot_stripes lineplot=Treu

### ISSUE THREAD

**Issue by zhaoyycrow** [open2c/coolpuppy#153]
The labels are overlapping and impossible to see in `plotpup.plot_stripes` with `line_plot=True`. The example in the notebook shows this problem. I reproduce the plot with other data and got the same issue. 

Below is the figure in the walkthrough
![image](https://github.com/open2c/coolpuppy/assets/40773345/cc5db2c3-4262-4bd9-98e5-d0a8a3261cd2)

By the way, it is possible to specify the min/max of the line plot? Thank you!

**Comment by efriman** [comment]
Thanks for pointing this out. I can't figure out why, it's a problem of recent matplotlib. For now you can solve it by downgrading to matplotlib==3.7.5

I will try to solve it further on.
