### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by ratheraarif** [open2c/coolpuppy#155]
I received the following error:
 `TypeError: unsupported operand type(s) for +: 'int' and 'str'`

when I execute the following code

`pup_MT = coolpup.pileup(clr_MT,  df_arm_p_pairs, features_format='bedpe',
                  trans=True, expected_df=trans_expected_MT, flank = 50000,
                     rescale=False)`

`df_arm_p_pairs ` file looks like this

<img width="1085" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/66868e9b-b414-4273-9722-699e4c0da3bd">

Actually I want to know the pileup of telomeric telomeric interaction. I can find the pile up of Centro Centro interaction for which the file looks similar. However, I receive the above error when I do so for telo telo

Any suggestion?

**Comment by ratheraarif** [comment]
Oh! there was a minor error I rectified that, however, I now got the different error


`ValueError: No chromosomes are in common between the coordinate
                   file and the cooler file. Are they in the same
                   format, e.g. starting with "chr"?
                   `

however, as I can see the chromnames match perfectly 

`clr_MT.chromnames` gives:

'chr1',
 'chr2',
 'chr3',
 'chr4',
 'chr5',
 'chr6',
 'chr7',
 'chr8',
 'chr9',
 'chr10',
 'chr11',
 'chr12',
 'chr13',
 'chr14',
 'chr15',
 'chr16'

and the `df_arm_p_pairs` file  also have same chromnames 

<img width="854" alt="image" src="https://github.com/open2c/coolpuppy/assets/46924431/a7573448-16f8-47b2-b9af-de2d2549abcf">

**Comment by efriman** [comment]
Your regions are then being filtered out for some reason. Can you try with format="bed", it should do the same the way you've constructed the peak file

**Comment by ratheraarif** [comment]
This again raises an obvious error:

`AssertionError: Column names must include chrom, start, and end `

<img width="841" alt="image" src="https://github.com/user-attachments/assets/180445a0-5e2d-4a44-a874-67ca4228b80c">

**Comment by ratheraarif** [comment]
I found a way to run the code. but instead of signal being aggregated at the centre its located at the corner like here.
<img width="292" alt="image" src="https://github.com/user-attachments/assets/749a8cc8-33bf-44d1-a281-ea32d6cfec00">

I am not sure how should I set the `flank`. Please note that these are the telomeres of yeast.

**Comment by Phlya** [comment]
Well, telomeres can not be in the center, since they are at the edges of chromosomes, this looks like a reasonable result. Feel free to reopen if needed.
