### ISSUE TITLE
Issue with Bed vs Bedpe feature format

### ISSUE THREAD

**Issue by LucasMcNU** [open2c/coolpuppy#158]
I'm not sure if this is an issue with my use of the Coolpuppy. I get different behavior depending on which regions I use. I'm trying to do telomeric trans pileups. Here's an example code snippet:

```shell
condA=MB
res=80

coolA=/projects/b1103/HIC_Macquarrie/Lucas/merged_cools/${condA}/${condA}_${res}kb_merged_filt.cool
expA=/projects/b1103/HIC_Macquarrie/Lucas/merged_cools/${condA}/contacts/${condA}.expected.trans.${res}kb.tsv
out_fileA=/projects/b1103/HIC_Macquarrie/Lucas/merged_cools/${condA}/contacts/

dir_ann=/projects/b1103/HIC_Macquarrie/Lucas/annotation/
dir_res=/projects/b1103/HIC_Macquarrie/Lucas/loops/

coolpup.py $coolA ${dir_ann}telomeres_all.bed --features_format bed  --rescale --rescale-size 99 --rescale-flank 0 --expected $expA --trans --outname ${out_fileA}${condA}_80kb_trans_all_tel_pileup.clpy
```

When I use a bed format like this for regions of interest:

```
chrom   start   end
chr1    1       5000000
chr3    1       5000000
chr4    1       5000000
chr5    1       5000000
chr6    1       5000000
chr7    1       5000000
```

I get the following pileup:
![MB_80kb_trans_all_tel_pileup](https://github.com/user-attachments/assets/aa76f77d-b448-4c4d-8e88-ed91ba065d9a)

However, when I use Bedpe format with the following code:

```
coolpup.py $coolA ${dir_ann}telomeres_all.bedpe --features_format bedpe  --rescale --rescale-size 99 --rescale-flank 0 --expected $expA --trans --outname ${out_fileA}${condA}_80kb_trans_all_tel_pileup.clpy

```

where telomeres_all.bedpe has the following format:

```
chrom1  start1  end1    chrom2  start2  end2
chr1    1       5000000 chr1    1       5000000
chr1    1       5000000 chr2    1       5000000
chr1    1       5000000 chr3    1       5000000
chr1    1       5000000 chr4    1       5000000
etc.. for all chromosomes ..
```
I get the following error: ``` ValueError: No chromosomes are in common between the coordinate ```

If I run the same code with a Bedpe that includes the entirety of the chromosome for chrom2 like this:

```
chrom1  start1  end1    chrom2  start2  end2
chr1    1       5000000 chr1    1       248866422
chr1    1       5000000 chr2    1       242103529
chr1    1       5000000 chr3    1       198205559
chr1    1       5000000 chr4    1       190124555
chr1    1       5000000 chr5    1       181448259
etc.. for all chromosomes ..
```
I get a very dilute pileup with no telomeric pileup in the left corner as expected.

My question is: 
#### what regions is the Bed including that the Bedpe is not including? Why are the results so different? 
This is not entirely clear from the documentation. I've tried this without rescaling and it seems to work best with reshaping the pileup. Also, im using Coolpuppy version 1.1.0.

**Comment by LucasMcNU** [comment]
Closing this as I see now that the issue was with not setting ``` --mindist 0 ``` . With this set, the Bed ROIs give the saem result as the Bedpe ROIs. For some chromosomes this seems to be necessary.

**Comment by Phlya** [comment]
OK, it's a bit surprising it would matter with --trans... I added some insurance just in case that sets mindist to 0 in case of trans in the latest commit, hopefully it prevents this issue from popping up in the future versions.

**Comment by LucasMcNU** [comment]
thanks!
