### ISSUE TITLE
KeyError: Can't use expected files generated by cooltools compute-expected

### ISSUE THREAD

**Issue by zhaoweiyu-github** [open2c/coolpuppy#22]
Hi Phyla, I wanted to use expected values generated by cooltools compute-expected rather than random shift control in pileup analysis, but  I encountered an error as follows:

Traceback (most recent call last):
  File "/mnt/Storage/home/yuzhaowei/anaconda3/envs/py37/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/mnt/Storage/home/yuzhaowei/anaconda3/envs/py37/lib/python3.7/site-packages/coolpuppy/__main__.py", line 440, in main
    ignore_diags=args.ignore_diags,
  File "/mnt/Storage/home/yuzhaowei/anaconda3/envs/py37/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 866, in __init__
    for chrom, region in self.regions.items()
  File "/mnt/Storage/home/yuzhaowei/anaconda3/envs/py37/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 866, in <dictcomp>
    for chrom, region in self.regions.items()
  File "/mnt/Storage/home/yuzhaowei/anaconda3/envs/py37/lib/python3.7/site-packages/cooltools/snipping.py", line 459, in select
    gr.get_group(tuple(region1))[
  File "/mnt/Storage/home/yuzhaowei/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 648, in get_group
    raise KeyError(name)
KeyError: ('chr1', None, None)

Here's the command line I executed:
1. cooltools compute-expected -p 10 -o ${sample}_expected.tsv ${sample}.scool
2. coolpup.py ${sample}.scool test.bed --local --expected ${sample}_expected.tsv

cooltools version: version 0.3.2
coolpup.py version: 0.9.5

Thanks all for your help!

**Comment by Phlya** [comment]
Hi, this is strange, I use expected normalization all the time and never had this problem.

Could you share what your expected file looks like?
Any reason why your cool file has .scool extension?

**Comment by Phlya** [comment]
Just wondering whether this recent change broke something for coolpuppy...
https://github.com/mirnylab/cooltools/pull/171

**Comment by zhaoweiyu-github** [comment]
Thanks for your help. I have recovered snipping.py in cooltools to the version before they changed for [snipping now selects correct regions from expected #171](https://github.com/mirnylab/cooltools/pull/171/files/ec2633fa4596e0a9cf0b6586872f1825f5bd2d1c) and it worked. So it seems like the recent change broke something for coolpup. I don't know whether it is a bug of cooltools as I'm not familiar with cooltools. If not, is it possible for you to provide a new version to match this change of cooltools?

**Comment by Phlya** [comment]
Yeah I'll try to figure out what changed there and fix it...

**Comment by zhaoweiyu-github** [comment]
I think it might be the difference between input expected tsv (tsv have only chrom column but not start,end) and calculated expected dataframe (have chrom,start,end column) like [cootools_error](https://github.com/gerlichlab/ngs/blob/new_cooltools/Cooltools_error.ipynb).

**Comment by zhaoweiyu-github** [comment]
I have submit a comment for the problem to developers of cooltools [KeyError in ObsExpSnipper for input expected tsv #177
](https://github.com/mirnylab/cooltools/issues/177).

**Comment by Phlya** [comment]
Thanks! For now you can just use cooltools from PyPI instead of master, but I'll sort it out for the future.

**Comment by Phlya** [comment]
This should now be fixed in the master!
