### ISSUE TITLE
Inter-chromosomal pileup?

### ISSUE THREAD

**Issue by tanlongzhi** [open2c/coolpuppy#24]
Hi Ilya,
Thanks a lot for your help last time!

I noticed that your README mentioned that inter-chromosomal pile-up will be available in the future. I was wondering when this new feature is expected. Thank you in advance!

Best,
Tan

**Comment by Phlya** [comment]
Hi Tan,

I know it's been a long time since your question, but @efriman has now implemented trans pileups in the master branch, if you are still interested! It's still a little "beta", but if you want to give it a try, it should work.

**Comment by tanlongzhi** [comment]
Hi Ilya,

Thank you and @efriman for implementing trans pileups!! I really appreciated your longstanding contribution to the field of 3D genomics, and congratulate you on your new position in the Giorgetti lab -- best wishes for your future research!

Best,
Tan
