### ISSUE TITLE
loops file in bed format

### ISSUE THREAD

**Issue by Ferossitiziano** [open2c/coolpuppy#26]
Good evening,

I am trying to run my first test with the coolpup.py command and I was wondering what kind of information should the CH12_loops_Rao.bed file contains. Are these the coordinates of the interactions reported in the Scc1-control.10000.cool file?

```
coolpup.py Scc1-control.10000.cool CH12_loops_Rao.bed --nshifts 10 --unbalanced --coverage_norm --mindist 100000 --outname Ctrl_loop.txt --log WARNING
```

thank you,

Federico

**Comment by Phlya** [comment]
Dear Federico,

This is a file with coordinates of loops from the CH12 cell line, from Rao et al 2014 publication. This is the data that was used in the original snHi-C papers, and shows clear enrichment in zygote data. Hope this helps!

Best wishes,
Ilya

**Comment by Ferossitiziano** [comment]
Dear Ilya,

thank you for your help, I was mostly wondering the format of the ```CH12_loops_Rao.bed``` file. I have now cloned the cool puppy repository and saw it is a 6 columns .bed format file. 

I generated a contact matrix using HiCpro, which contains all the valid pairs of my dataset (see below). I then converted this matrix in a  .cool file.

```

A00302:209:HNTYLDMXX:1:1101:1407:27070	chr10	8366768	-	chr18	33310142	-	104	HIC_chr10_13409	HIC_chr18_75848	37	15
A00302:209:HNTYLDMXX:1:1101:1470:9330	chr13	37410778	-	chr13	37419443	+	140	HIC_chr13_87004	HIC_chr13_87031	42	42
A00302:209:HNTYLDMXX:1:1101:1570:32706	chr10	98850582	-	chr10	118002409	+	128	HIC_chr10_237733	HIC_chr10_283362	42	42

```

and I was wondering how I could obtain a file similar to ```CH12_loops_Rao.bed``` by using my data.

Thank you,

Federico

**Comment by Phlya** [comment]
If you want to annotate peaks (loops) in your data, you can try `cooltools call-dots`. Other tools that work with cool files are mustache and chromosight (and maybe others).
