### ISSUE TITLE
Using API: AttributeError: 'CoordCreator' object has no attribute 'final_chroms'

### ISSUE THREAD

**Issue by cmdoret** [open2c/coolpuppy#27]
Hi,

I planned to use coolpuppy (v0.9.5) to extract windows from a cool file around each pair of genes in a bed file.
Since I was working in a jupyter notebook, it was more convenient to use the API.

So from my understanding, the first step is to create a PileUpper object. I did the following:

```python
import coolpuppy as clp
clp.PileUpper(clr_ctl, clp.CoordCreator(TMP_BED, resolution = clr_ctl.info['bin-size']))
```
The `CoordCreator` can be initialized, but then `PileUpper` requests its `final_chroms` attribute which has not been set. It raises an AttributeError with the following traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-59-f08a42692e8b> in <module>
      7 bed.end = bed.end.astype(int)
      8 bed.to_csv(sep='\t', header=False, index=False)
----> 9 clp.PileUpper(clr_ctl, clp.CoordCreator(TMP_BED, resolution = clr_ctl.info['bin-size']))

~/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py in __init__(self, clr, CC, balance, expected, control, coverage_norm, rescale, rescale_pad, rescale_size, ignore_diags)
    849 
    850         self.chroms = natsorted(
--> 851             list(set(self.CC.final_chroms) & set(self.clr.chromnames))
    852         )
    853         self.regions = {

AttributeError: 'CoordCreator' object has no attribute 'final_chroms'

```

I noticed the object created by CoordCreator does not have a `bases` attribute either, although it should have been created here, so I don't really understand what went wrong:
https://github.com/open2c/coolpuppy/blob/198ca7cc85fc5ab5584a6c65355ba473ba1dd73a/coolpuppy/coolpup.py#L704

Did I misuse the API ? Or should I just stick with the CLI ? 

Cheers

**Comment by Phlya** [comment]
Hy Cyril, I think you need to update coolpuppy... I think the latest version hasn't been uploaded to PyPI yet, I should get to that. Can you reinstall it from github and try again?

**Comment by Phlya** [comment]
Alternatively, manually call `CC.process()` before using it.

**Comment by cmdoret** [comment]
Thanks @Phlya, using the latest coolpuppy version _and_ calling CC.process() manually did solve the problem !

**Comment by Phlya** [comment]
Did you have to do both?  With the latest version .process() is called in __init__(), so shouldn't be needed separately.

**Comment by cmdoret** [comment]
My bad, you're right (I was in the wrong environment), the master version calls process automatically as expected.

**Comment by Phlya** [comment]
Great, thanks for confirming! Hope it all works for you, you are probably the first person apart from me to try the API.
