### ISSUE TITLE
How to get individual pile-up results ? 

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/coolpuppy#28]
Hi :
    Thanks for developing such a helpful tool!
    Now I want to calculate individual TAD structure strength by the interactions within-TAD over the between-TAD intensity, so I need to get individual pile-up results for each TADs. Maybe I can do it with some options? I don't know how to do it, could you give me some suggestions?
     Thanks in advance!

Best wishes
Qianzhao

**Comment by Phlya** [comment]
Dear Qianzhao,

Unfortunately, coolpuppy is designed not to retain information about individual features, and there is no way to do it using coolpuppy. However, it sounds like what you want to do is quite easily achievable using `cooler` directly if you have any experience using python.
Alternatively, perhaps using insulation score from `cooltools` would help you, if you are interested in boundary strength.

If you provide more details about what analysis exactly you want to perform, it'll be easier to suggest the exact ways to do it.

**Comment by QianzhaoJ** [comment]
Dear Phlya,
Thanks for your quick reply!
I wanted to follow the analysis like descriptions in [this paper](https://www.nature.com/articles/s41586-019-1812-0) (**TAD structure strength** in **Methods** part). I think it can be done easily using `coolpuppy` if I can extract rescaled information for individual TADs.
Thanks a lot.

Qianzhao

**Comment by Phlya** [comment]
From what I can tell from their methods, the TAD structure strength is calculated over a rescaled pileup, just like in our 2017 paper, so you wouldn't need information about individual TADs. You can just create a rescaled pileup, and then calculate the strength from the output matrix. AM I misunderstanding something?

**Comment by QianzhaoJ** [comment]
Dear Phlya,
"the TAD structure strength is calculated over a rescaled pileup" is right, but I don't want to get the overall TAD structure strength.
I want to get TAD structure strength for each TAD. I think it can reflect the difference in TAD structure when comparing different hic data. If one TAD structure strength significantly changed, maybe the transcriptional activity in this TAD would also change, so some downstream analysis can be done.

Qianzhao

**Comment by Phlya** [comment]
Right, OK - in that case if you want to do it exactly like that but for individual TADs, coolpuppy can't help you, unfortunately. But you can quite easily do it using python and cooler API.

**Comment by QianzhaoJ** [comment]
Dear Phlya,
Thanks for your help! I have figured it out basically. 
By the way , what's the format of input bed file for averaged insulation score valleys? I called the TAD boundaries using cworld (insulation scores), and use the location of boundaries i.e. chr1 150000 160000 for local pileups, but the final plot is strange as like 
![image](https://user-images.githubusercontent.com/42069662/100525828-818eb680-31fe-11eb-9dde-e20c542de040.png)

Bests
Qianzhao

**Comment by Phlya** [comment]
I'd need more details to help you I think. It should be just a bed file with three columns.
How are you plotting it? Is it possible you just need to set a wider colour range?

**Comment by QianzhaoJ** [comment]
The command "coolpup.py $cool $bed --local --outname WT_B.txt --log WARNING --n_proc 24 && plotpup.py boundary.txt --row_names WT --output WT_tad.pdf" 
The boundaries bed file:
[b.location.txt](https://github.com/open2c/coolpuppy/files/5611240/b.location.txt)
And I have tried `Rescaled pileups`, this result looks normal.

**Comment by Phlya** [comment]
Try changing the --vmin or --vmax in the plotting command, does that help? Or, can you share the `WT_B.txt` file?

**Comment by QianzhaoJ** [comment]
Of course. I am going to change the range of colours. 
The output of coolpup.py :
[WT_B.txt](https://github.com/open2c/coolpuppy/files/5611251/WT_B.txt)

**Comment by Phlya** [comment]
With --vmax 2.
I guess I need to check the autoscaling in plotpup.py, sorry about the confusion - but at least your output makes sense!
![image](https://user-images.githubusercontent.com/2895034/100526306-7ff1ce00-31bf-11eb-9e23-cda55edbe0a7.png)

**Comment by QianzhaoJ** [comment]
Thanks a lot for your help! However, I thought the zero values in the diagonal looks strange, could you explain it a little?

**Comment by Phlya** [comment]
The first two diagonals are ignored by default, since they tend to contain a lot of artefacts, and are generally ignored in all analyses.

**Comment by QianzhaoJ** [comment]
I got it! Thank you for your explanation! 
Another question is can I set the range up and downstream of TAD boundaries when using coolpup.py? as like 100kb or more?

**Comment by Phlya** [comment]
Yep, use the --pad argument (in kbp).

**Comment by QianzhaoJ** [comment]
Dear Phlya,
That's a wonderful tip! When I set "--pad 300", the final plot looks make sense!
![image](https://user-images.githubusercontent.com/42069662/100526727-a0914680-3206-11eb-9b55-62b89e6d6285.png)
Thanks a lot again!

Best wishes 
Qianzhao

**Comment by Phlya** [comment]
That looks much better, well done finding the right setting!
