### ISSUE TITLE
--local giving weird result

### ISSUE THREAD

**Issue by prullens** [open2c/coolpuppy#30]
Hi,

I'd like to use ```coolpup.py``` to visualize local insulation valleys in the Hi-C matrix. However, running the following command ```coolpup.py mESC.cool mESC_tadcalls.bed --local``` results in weird output:
![afbeelding](https://user-images.githubusercontent.com/45201783/106451390-ce08a380-6486-11eb-839e-917bada70246.png)

While running ```coolpup.py mESC.cool mESC_tadcalls.bed --rescale --local```  works just fine:
![afbeelding](https://user-images.githubusercontent.com/45201783/106451666-2a6bc300-6487-11eb-9d93-46d5a501bbc9.png)

I tried tweaking the ```--pad``` parameter, but without any improvements.

Hi-C data is binned at 10kb.

Best,

**Comment by Phlya** [comment]
Looks like you are using tad coordinates, when you actually want to use coordinates of insulation boundaries.

**Comment by prullens** [comment]
Thanks for your quick reply. Really appreciated! 

Yes, I am using TAD coordinates, but the TADs were called based on insulation valleys. In general, should TAD coordinates not very closely represent insulation valleys, regardless of the way one may have called TADs? 

But perhaps the ```bed``` file should be different when analyzing the insulation valleys using ```--local```?

**Comment by Phlya** [comment]
Yes, the bed file should be different - it should contain coordinates of the insulation valleys. Currently you are averaging centres of TADs, while you want to average their boundaries. So if you created TADs by combining consecutive boundaries, use the original boundary coordinates.

**Comment by prullens** [comment]
Ahh! I get what you mean. So just the start and the end of the bin of the local insulation valley. Thanks for helping and developing this very useful tool!

**Comment by Phlya** [comment]
Exactly! Glad I could help.

**Comment by prullens** [comment]
It's working nicely now! But perhaps on a related note: do you ever see something similar to this
![afbeelding](https://user-images.githubusercontent.com/45201783/106488857-6f5a1e80-64b4-11eb-8bab-49e0ed51810c.png)

What I mean is that the signal in the lower right is stronger than in the upper left. This shouldn't be the case right? Do you think this may be an artifact of the randomization or do you have any thoughts on what else it may be?  If you look at the ```--rescale``` plot in my original post you'd also see the differences between the domain left to the TAD and right to the TAD. In the domain left to the TAD, the extrusion indicative stripes become visable.

**Comment by Phlya** [comment]
Mh, I'm glad it's working, but no, I don't normally see anything like this. How did you find the insulating boundaries?

**Comment by prullens** [comment]
Mm yeah perhaps not in the best way possible. I computed the insulation score myself according to Crane et al. 2015, and subsequently detected valleys using ```scipy.signal.find_peaks```. This was before I really learned about all the different tools available. I do seem to accurately find the valleys though. But maybe I should redo it with e.g. ```cooler```

**Comment by Phlya** [comment]
Try `cooltools diamond-insulation`

**Comment by prullens** [comment]
I will, thanks!

**Comment by Phlya** [comment]
You might want to explore this: https://github.com/open2c/open2c_examples/blob/master/Insulation_and_boundaries.ipynb

You can calculate the insulation using the command line, but you should also filter the called boundaries manually.

**Comment by prullens** [comment]
Thanks for the suggestion. I'll look into it! ```cooltools diamond-insulation``` works nicely :)
