### ISSUE TITLE
Local pileups and strandness

### ISSUE THREAD

**Issue by fgualdr** [open2c/coolpuppy#33]
Hi,

I am very interested in using your tool for pileup analysis.
I was trying to figure out whether is possible to do Local pileups in a strand aware manner.
In particular I am trying to get the average interactions not across TADs but across genes so from the TSS to the TES. For this purpose I should flip each matrix accordingly to the strangeness of the gene.
Do you think is doable with coolpuppy?
Thanks,

Francesco

**Comment by Phlya** [comment]
Hi Francesco,

Excellent question. At the moment with the latest version of coolpuppy available from github you can do pileups separately for two strands, easily with either CLI (`--by_strand`) or using Python API (see latest docs). Using Python API and a custom postprocessing function for each snip, you could flip regions on the negative strand to get them all in one orientation. Are you familiar with python and numpy?

Possibly, flipping the start and end coordinates would simply achieve it for you for free, but I haven't checked if that works (it might error or simply filter out inverted regions...). I'll look into that.

**Comment by kimj50** [comment]
Hi,
Thank you for the amazing tool. I was also hoping to be able to do strand-specific local pile-up.
version used: 
 /scratch/kimj50/singularity/coolpup.bash coolpup.py -v
0.9.5

cool file used: used juicer pipeline to make .hic file, which was used to convert to cool file using hicexplorer

I have no background in python. I did try following the walkthrough for coolpup and cooltools.
I tried flipping the start and end columns and gives the following error:

[kimj50@gr041 pileups]$ /scratch/kimj50/singularity/coolpup.bash coolpup.py /scratch/kimj50/juicerToh5/mcool/JK07_JK08_1000_KR.cool bed3_flip.bed --rescale --local
Namespace(anchor=None, baselist='groseq_L3_ce10Lift_5kbplus_bed3_flip.bed', bed2=None, bed2_ordered=True, by_window=False, coolfile='/scratch/kimj50/juicerToh5/mcool/JK07_JK08_1000_KR.cool', coverage_norm=False, excl_chrs='chrY,chrM', expected=None, ignore_diags=2, incl_chrs='all', local=True, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='.', outname='auto', pad=100, post_mortem=False, rescale=True, rescale_pad=1.0, rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=False, weight_name='weight')
Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/ext3/miniconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/ext3/miniconda3/lib/python3.8/site-packages/coolpuppy/__main__.py", line 428, in main
    CC.process()
  File "/ext3/miniconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 734, in process
    raise ValueError(
ValueError: No chromosomes are in common between the coordinate
                   file/anchor and the cooler file. Are they in the same
                   format, e.g. starting with "chr"?
                   Alternatively, all regions might have been filtered
                   by distance/size filters.

I was wondering if this has been solved. If not, maybe if you could share your python notebook...
Thank you!
Jun Kim

**Comment by Phlya** [comment]
Hi Jun Kim,

Two points first.
Could you try installing the latest version from github? `python -m pip install  https://github.com/open2c/coolpuppy/archive/refs/heads/master.zip`
You shouldn't be running the coolpup.py script directly - you need to install it as a python module and it should work from any directory by just calling `coolpup.py`

Then. Are you sure the chromosomes in the bed file match the chromosomes in the cool file? I.e. what does the bed file look like, and what does `cooler dump -t chroms <cooler> show?

**Comment by kimj50** [comment]
Thank you for the quick reply.
It looks like I screwed up the bed file.
swapping start and end column for minus strand works well.
Thank you !
Jun

**Comment by Phlya** [comment]
Does that actually work? I have been meaning to check that but haven't got around to that. Good news if that works!

**Comment by kimj50** [comment]
I think it did (simply going by the how the plots look). 
![image](https://user-images.githubusercontent.com/47995646/118305412-ee002800-b4b5-11eb-9367-eb5cc40fe1fc.png)

**Comment by Phlya** [comment]
Nice, that looks promising, thanks for sharing!

**Comment by Phlya** [comment]
Just FYI, I think actually this won't work with the most recent version, but there you can just annotate strands and make separate pileups for each strand. I'll look into making flipping the negative strand regions easier for a single pileups in the end, but I am probably not a fan of the idea to use start < end to do that, I'd prefer explicit strand annotation...

**Comment by kimj50** [comment]
Thanks for letting me know. Meantime, I guess i'll stick to the older version for visualizing.
Also, is there a reason why the 'padding' region for rescaled local pileup is proportional to the region of interest provided by bed file? (as opposed to fixed up/down bp similar to deeptools computeMatrix 'scale-regions' option)

**Comment by Phlya** [comment]
The padding for rescaled pileups is fractional, I think it makes more sense
for must use cases... Fixed length padding with rescaling is trickier to
implement as well.

**Comment by Phlya** [comment]
Flipping of negative strand features is implemented now in both python API and CLI!
