### ISSUE TITLE
plotpup.py error : UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by sweetymeel** [open2c/coolpuppy#34]
I used the following command to plot results obtained from coolpup.py (.txt files)
plotpup.py asyn_bs.txt mitt0_bs.txt mitt3_bs.txt mitt9_bs.txt mitt12_bs.txt --row_names asyn,mitt0,mitt3,mitt9,mitt12 --enrichment 0 --output all.png
**but it gave the following error;**
_Traceback (most recent call last):
  File "/softwares/python36/bin/plotpup.py", line 11, in <module>
    load_entry_point('coolpuppy==0.9.7', 'console_scripts', 'plotpup.py')()
  File "/softwares/python36/lib/python3.6/site-packages/coolpuppy-0.9.7-py3.6.egg/coolpuppy/__plotpuppy_main__.py", line 147, in main
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/softwares/python36/lib/python3.6/site-packages/coolpuppy-0.9.7-py3.6.egg/coolpuppy/__plotpuppy_main__.py", line 147, in <listcomp>
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/softwares/python36/lib/python3.6/site-packages/coolpuppy-0.9.7-py3.6.egg/coolpuppy/coolpup.py", line 103, in load_array_with_header
    read_data = f.read()
  File "/softwares/python36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte_

Can someone please help me in resolving the issue?

**Comment by Phlya** [comment]
Were you using the latest version from GitHub? At the moment coolpup.py script is a little out of sync with the main code, where the storage format actually changed and it isn't a simple text file anymore. Sorry about that, fixing the plotting script is next on my list. Are you familiar with python? You could load the data manually and plot it.

**Comment by sweetymeel** [comment]
@Phlya  Thanks a lot! Sorry but am new to python so won't be able to do manual plotting immediately. I will check the version though. 
Also, the same function works fine on another system of mine, you think it is a version issue only? 
One difference I noted was the .txt file obtained from coolpup.py is a readable matrix sort of file in this case.

**Comment by Phlya** [comment]
Yeah just a version issue - the storage format changed, and in the newest version it's not a text file anymore, so that's why the plotting script doesn't work with the new output anymore.

**Comment by sweetymeel** [comment]
Okay. Hoping to see the new plotting version soon. Till then I will try to figure out the manual plotting ways as you had suggested.
Thanks again.
