### ISSUE TITLE
UserWarning: No regions in baselist, returning empty output

### ISSUE THREAD

**Issue by sweetymeel** [open2c/coolpuppy#35]
I am trying to use an mcool file in coolpup.py
_the command and result for which are as follows:_

coolpup.py '4DNFIO4E7KQP.mcool::/resolutions/500000' /home/sweety/Documents/H3S10p_2020/coolpuppy/127_tads_subtads_having_h3s10p_during_mitosis.txt --nshifts 10 --rescale --local --unbalanced --coverage_norm --rescale_size 87 --outname mitt0127tad
Namespace(anchor=None, baselist='/home/sweety/Documents/H3S10p_2020/coolpuppy/127_tads_subtads_having_h3s10p_during_mitosis.txt', basetype='auto', bed2=None, bed2_ordered=True, by_window=False, coolfile='4DNFIO4E7KQP.mcool::/resolutions/500000', coverage_norm=True, excl_chrs='chrY,chrM', expected=None, ignore_diags=2, incl_chrs='all', local=True, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='.', outname='mitt0127tad', pad=100, post_mortem=False, rescale=True, rescale_pad=1.0, rescale_size=87, save_all=False, seed=None, subset=0, unbalanced=True, weight_name='weight')
NumExpr defaulting to 8 threads.
**/home/sweety/.local/lib/python3.8/site-packages/coolpuppy/coolpup.py:721: UserWarning: No regions in baselist, returning empty output
  warnings.warn("No regions in baselist, returning empty output")**
Saved output to /media/sweety/SweetyMeel_2020_HD1/abramo2019_rep1_processed_files/mitt0127tad

Can someone please tell why am I getting am empty output? I have checked the text file already and it works fine with other .cool files.

**Comment by Phlya** [comment]
Very strange, but I don't think I can help you without more information, like can you share the file?
What jumps out at me though is that you are using very low resolution (500 000), perhaps if all regions are shorter than that it would be an issue... I haven't considered this possibility, not sure what would happen. Does it work with higher resolution? I don't see any reason to make pileups with 500kb resolution anyway...

**Comment by sweetymeel** [comment]
Thanks a lot @Phlya  
The issue got resolved. The problem was the format incompatibility of the text file and the mcool file itself. And as far as the 500kb resolution is concerned I was just trying to do it for a set of resolutions.
