### ISSUE TITLE
issue with coolpup.py

### ISSUE THREAD

**Issue by faryabib** [open2c/coolpuppy#36]
Hi, I just installed the latest version of coolpuppy and have an issue with coolpup.py output. 

The previous version would generate a text output, while the latest version generates a binary output file. It also issues a warning:

/mnt/data0/apps/anaconda/ana2/envs/p3/lib/python3.7/site-packages/pandas/core/generic.py:2715: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->integer,key->block0_values] [items->Index(['n'], dtype='object')]

  encoding=encoding,

**Comment by Phlya** [comment]
That is correct, the output format has changed, and the warning is nothing serious. Please explain what is your issue exactly?

**Comment by faryabib** [comment]
Our pipelines use the ascii output for downstream plotting and other analysis. Is there a way to get the text output instead? Or let me know how I could install the final version that outputs text file.

**Comment by Phlya** [comment]
I think if you just install it from PyPI it will have the old behaviour, the new storage format is not released yet.
Alternatively, if your pipleline is in python, you can just try to read the new files using this function: https://github.com/open2c/coolpuppy/blob/e99432ec406f1eeaa622f4efbf0c9c0963baf09d/coolpuppy/coolpup.py#L67

Just to explain, the new versions can calculate many pileups in one go, and saving many of them in one text file doesn't really work, moreover reading many text files can be very slow. So I switched the output format to hdf5-based, which can store many pileups together with the annotations.

**Comment by Phlya** [comment]
Let me know if I can help with anything, closing.
