### ISSUE TITLE
Coolpuppy Jupyter notebook seems outdated

### ISSUE THREAD

**Issue by gabedolpten** [open2c/coolpuppy#37]
Hi, I am trying to run coolpuppy API through the jupyter notebook, but it seems to be outdated. For example, basetype='bed', seems to no longer be an argument for cp.CoordCreator. Is there a link to an updated walkthrough for the API?

**Comment by Phlya** [comment]
I think it's the opposite problem: the version with basetype argument is not released yet! Sorry, there are big changes, and I didn't want to make a release before everything is ready, and it's taking a long time.
Try installing the latest version from gihub, and the notebook should work - although I haven't checked recently in case something minor has changed.

**Comment by gabedolpten** [comment]
Oh ok great! I will try that :-)
I am relatively new to compbio so I see you are using bbi and bioframe in your notebook, which seem quite useful. I have been doing everything in pyBedTools and pyBigWig so far – will I still be able to pass in pyBedTool objects to coolpuppy?

**Comment by Phlya** [comment]
No sorry! You'll have to convert it to a dataframe first.

**Comment by Phlya** [comment]
Now the notebooks and the latest version on github are in sync, closing, let me know if anything is unclear.
