### ISSUE TITLE
ValueError: TSV schema not found: 'bedpe'

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/coolpuppy#42]
Hi :
Thanks for developing such a helpful tool!
I re-installed the lastest coolpup.py(v0.9.7), but when I tried it in my `.cool` files , I got some errors: `ValueError: TSV schema not found: 'bedpe'`.

My codes:
`coolpup.py $cool $bedpe --outname ${sample}_loop.txt --log WARNING --n_proc 24`
and the version of cooltools=0.4.1;  the version of cooler =0.8.5
the bedpe file as follows:

```
chr1	1323000	1332000	chr1	1431000	1440000
chr1	6105000	6116000	chr1	6391000	6402000
chr1	6762000	6776000	chr1	7126000	7140000
```
Thanks in advance!
Best wishes
Qianzhao

**Comment by Phlya** [comment]
Hi Qianzhao,

You need the latest version of bioframe, that's where the schemas are from.

**Comment by QianzhaoJ** [comment]
Hi
Thanks for quick reply!
I tried to update my bioframe using `pip install bioframe==0.3.0`, some issues still exists.
When I use codes as follows:
`coolpup.py $cool $bedpe --expected $mat --outname ${sample}_loop.txt --log WARNING --n_proc 24`
It works and I got some warnings:
```
/share/home/jiqianzhao/anaconda3/envs/cool/lib/python3.7/site-packages/pandas/core/generic.py:2718: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->integer,key->block0_values] [items->Index(['n'], dtype='object')]
```
and I found the output of coolpup.py is a binary file, is it normal changes in lastest version?

When I use my expected matrix as follows:
`coolpup.py $cool $bedpe --expected $mat --outname ${sample}_loop.txt --log WARNING --n_proc 24`
I got a new error: 
`TypeError: __init__() got an unexpected keyword argument 'view_df'`

Best wishes
Qianzhao

**Comment by Phlya** [comment]
You can ignore the warnings.

Indeed, the output format has changed! I's now based on hdf5.

Can you share the full error? What do you mean by the expected "matrix"?

**Comment by Phlya** [comment]
Ah, I think you need to update cooltools. Get the latest version from github, not from PyPI. It'll be released soon, but not yet... That's one of the reasons this version of coolpuppy isn't released yet.

**Comment by QianzhaoJ** [comment]
Hi,
Sorry for for my unclear description. The expected matrix is actually the tsv file output of ``cooltools compute-expected``.
I update my cooltools to the lastest using `pip install https://github.com/open2c/cooltools/archive/refs/heads/master.zip` and I re-caculate the expected tsv file using `cooltools compute-expected`,
and re-run `coolpup.py $cool $bedpe --expected $mat --outname ${sample}_loop.txt --log WARNING --n_proc 24`
I got a new error:

```
Traceback (most recent call last):
  File "/share/home/jiqianzhao/anaconda3/envs/cool/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/share/home/jiqianzhao/anaconda3/envs/cool/lib/python3.7/site-packages/coolpuppy/__main__.py", line 452, in main
    ignore_diags=args.ignore_diags,
  File "/share/home/jiqianzhao/anaconda3/envs/cool/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1286, in __init__
    "Please provide the view_df table, if region names"
ValueError: Please provide the view_df table, if region namesare not simply chromosome names.
```

Another question, for the lastest coolpup, I'm not familiar with `hdf5` format, could you give me some help if I wanted to extract the pileup matrix (tsv format,the output of older version) for visualization in R.
Thanks a lot!

Best wishes
Qianzhao

**Comment by Phlya** [comment]
How do you run expected? What are your chromosomes named, do you specify a view/regions when running expected?

Mh at the moment there is no simple way to extract data from the hdf5 files coolpuppy creates, because the output is very flexible internally - that's why I switched to this format. In python you can read it using coolpup.load_pileup_df, and then you can save it to a text file. But the trick is saving the annotations together with the pileup, and the file can have many pileups stored at the same time... So it's possible, but there is no code that does it yet. For a single pileup it would be quite easy, I can write it. Or you can try using the plotpup.py tool?

**Comment by QianzhaoJ** [comment]
Hi,
I got expected tsv file using `cooltools compute-expected $cooler --contact-type cis -p 24 -o $out/$sample/${sample}_expected.${res}.cis.matrix` .
Now I have downgraded my cooltools (v0.3.2) and coolpup(v0.9.5), It works.
For the lastest coolpup, it would be helpful to export the final average pileup matrix ,I hope you can add a parameter. And I will learn how to use the "hdf5" format.
Thanks for your help !
Best wishes
Qianzhao

**Comment by Phlya** [comment]
I need to test it, but I think I might have fixed the latest error you were getting...

I'll look into dumping text files, but the whole point of the new format was to move away from them!

**Comment by Phlya** [comment]
I just uploaded a tutorial how to use the CLI of the new version: https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html
Perhaps this can help you plot using the plotpup.py command using new files?

**Comment by QianzhaoJ** [comment]
I will try it and Thanks for your patient help !

Best,
Qianzhao
