### ISSUE TITLE
Hi-C interaction enrichment between enhancers and promoters

### ISSUE THREAD

**Issue by QianzhaoJ** [open2c/coolpuppy#43]
Hi,
I want to analyze the interactions between enhancer signals (like H3K27ac peak) and promoter signals (like H3K4me3 peak), as shown in this [article](https://doi.org/10.1016/j.molcel.2020.03.002)
![image](https://user-images.githubusercontent.com/42069662/134617927-e7dd1086-c28c-4937-b002-4bbc4151b3f4.png)

I found the "--bed2"  argument in coolpuppy (version 0.9.5), and I thought it would be helpful , but I also found  that the argument has been removed in the lastest version coolpuppy (0.9.7). Is there something wrong with the argument?  Could I implement my idea using the "--bed2"  argument?
Thanks in advance !

Best,
Qianzhao

**Comment by Phlya** [comment]
Hi Qianzhao,

Good question! the --bed2 feature was a bit annoying to maintain in the code, so I removed it in this big update. However the new features introduced allow one to do the same, and even more: i.e. effectively, any number of pairs files can be used at the same time, although it's a bit restricted in the CLI and very flexible in the python API at the moment. The idea is that you can combine any number of files you want and annotate which dataset each row is coming from in a particular column. Then you can group the snippets by that column, and therefore produce multiple pileups with one command. In the CLI at the moment a special case is implemented for by-strand grouping, and you could use that for your purposes: code promoters as + and enhancers as -, for example, and then the result will have all different combinations. Check the notebooks in the docs for more details. Hope this helps!

Ilya

**Comment by Phlya** [comment]
Closing, let me know if there any more questions!
