### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by chenggang108** [open2c/coolpuppy#51]
Hi @Phlya,

I am interested in the coolpuppy. Every thing looks Ok when I do the installation following the instruction. But it show error when I run the program.  It showed as "ValueError: numpy.ndarray size changed, may indicate binary incompatibility".

I tried to use different version of numpy, but the problem is not resolved. Could you please help with it?

Thanks

**Comment by Phlya** [comment]
Hi, are you using conda? I would try a clean environment... I've never encountered this issue, so not entirely sure what is the problem.

**Comment by chenggang108** [comment]
Thank you for your swift response. Yes, I use conda to create an environment and install everything under the environment. I will try some different ways.
Best

**Comment by chenggang108** [comment]
Hi @Phlya,

A follow up of my question and a new quick question.
The problem resolved by creating a new environment and install all the requirement with conda. It is possible that there are some conflicts between pip and conda installation.

A new question:
The coolpuppy is installed by "pip install coolpuppy", 
coolpup.py -v shows "0.9.5"
But the coolpup.py -h show different information from the one shows on coolpup.py CLI
The version on coolpup.py CLI makes more sense for me, because there is a bedpe option. Could you please explain a little bit?

The following is how it shows of my coolpup.py -h



usage: coolpup.py [-h] [--bed2 BED2] [--bed2_unordered] [--pad PAD] [--minshift MINSHIFT] [--maxshift MAXSHIFT] [--nshifts NSHIFTS] [--expected EXPECTED] [--mindist MINDIST] [--maxdist MAXDIST]
                  [--ignore_diags IGNORE_DIAGS] [--minsize MINSIZE] [--maxsize MAXSIZE] [--excl_chrs EXCL_CHRS] [--incl_chrs INCL_CHRS] [--subset SUBSET] [--anchor ANCHOR] [--by_window] [--save_all]
                  [--local] [--unbalanced] [--coverage_norm] [--rescale] [--rescale_pad RESCALE_PAD] [--rescale_size RESCALE_SIZE] [--weight_name WEIGHT_NAME] [--n_proc N_PROC] [--outdir OUTDIR]
                  [--outname OUTNAME] [--seed SEED] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--post_mortem] [-v]
                  coolfile baselist

positional arguments:
  coolfile              Cooler file with your Hi-C data
  baselist              A 3-column bed file or a 6-column double-bed file i.e. chr1,start1,end1,chr2,start2,end2. Should be tab-delimited. With a bed file, will consider all cis combinations of
                        intervals. To pileup features along the diagonal instead, use the ``--local`` argument. Can be piped in via stdin, then use "-"

optional arguments:
  -h, --help            show this help message and exit
  --bed2 BED2           A 3-column bed file. Should be tab-delimited. Will consider all cis combinations of intervals between baselist and bed2 (default: None)
  --bed2_unordered      Whether to use baselist as left ends, and bed2 as right ends of regions (default: True)
  --pad PAD             Padding of the windows around the centres of specified features i.e. final size of the matrix is 2×pad+res, in kb. Ignored with ``--rescale``, use ``--rescale_pad`` instead
                        (default: 100)
  --minshift MINSHIFT   Shortest shift for random controls, bp (default: 100000)
  --maxshift MAXSHIFT   Longest shift for random controls, bp (default: 1000000)
  --nshifts NSHIFTS     Number of control regions per averaged window (default: 10)
  --expected EXPECTED   File with expected (output of ``cooltools compute-expected``). If None, don't use expected and use randomly shifted controls (default: None)
  --mindist MINDIST     Minimal distance of interactions to use, bp. If not specified, uses 2*pad+2 (in bins) as mindist (default: None)
  --maxdist MAXDIST     Maximal distance of interactions to use (default: None)
  --ignore_diags IGNORE_DIAGS
                        How many diagonals to ignore (default: 2)
  --minsize MINSIZE     Minimal length of features to use for local analysis (default: None)
  --maxsize MAXSIZE     Maximal length of features to use for local analysis (default: None)
  --excl_chrs EXCL_CHRS
                        Exclude these chromosomes from analysis (default: chrY,chrM)
  --incl_chrs INCL_CHRS
                        Include these chromosomes; default is all. ``--excl_chrs`` overrides this (default: all)
  --subset SUBSET       Take a random sample of the bed file. Useful for files with too many featuers to run as is, i.e. some repetitive elements. Set to 0 or lower to keep all data (default: 0)
  --anchor ANCHOR       A UCSC-style coordinate. Use as an anchor to create intersections with coordinates in the baselist (default: None)
  --by_window           Perform by-window pile-ups. Create a pile-up for each coordinate in the baselist. Will save a master-table with coordinates, their enrichments and corner coefficient of
                        variation, which is reflective of noisiness (default: False)
  --save_all            If ``--by-window``, save all individual pile-ups in a separate json file (default: False)
  --local               Create local pileups, i.e. along the diagonal (default: False)
  --unbalanced          Do not use balanced data. Useful for single-cell Hi-C data together with ``--coverage_norm``, not recommended otherwise (default: False)
  --coverage_norm       If ``--unbalanced``, add coverage normalization using chromosome marginals (default: False)
  --rescale             Rescale all features to the same size. Do not use centres of features and pad, and rather use the actual feature sizes and rescale pileups to the same shape and size
                        (default: False)
  --rescale_pad RESCALE_PAD
                        If --rescale, padding in fraction of feature length (default: 1.0)
  --rescale_size RESCALE_SIZE
                        Size to rescale to. If ``--rescale``, used to determine the final size of the pileup, i.e. it will be size×size. Due to technical limitation in the current implementation,
                        has to be an odd number (default: 99)
  --weight_name WEIGHT_NAME
                        Name of the norm to use for getting balanced data (default: weight)
  --n_proc N_PROC       Number of processes to use. Each process works on a separate chromosome, so might require quite a bit more memory, although the data are always stored as sparse matrices
                        (default: 1)
  --outdir OUTDIR       Directory to save the data in (default: .)
  --outname OUTNAME     Name of the output file. If not set, it is generated automatically to include important information (default: auto)
  --seed SEED           Set specific seed value to ensure reproducibility (default: None)
  -l {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --log {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set the logging level (default: INFO)
  --post_mortem         Enter debugger if there is an error (default: False)
  -v, --version         show program's version number and exit

**Comment by Phlya** [comment]
Sorry about the confusion - the online docs are for the latest unreleased version which is available from GItHub. There have been very big changes and some more are planned, and I will then release version 1.0. I'll investigate whether I can enable online docs specifically for released versions...

**Comment by chenggang108** [comment]
Thank you for the explanation. The online docs does make more sense for me. Hope it can be release soon.

**Comment by chenggang108** [comment]
Hi @Phlya,

Is there a function that can compare two pileup data. I found that it is useful to show the difference between two stages like GENOVA does.

Thanks

**Comment by Phlya** [comment]
You can just compare two pileups manually in Python. There is no ready functions, sorry.
