### ISSUE TITLE
Can't import snipping from cooltools

### ISSUE THREAD

**Issue by cpadillla1331** [open2c/coolpuppy#52]
Hello, 

I ran this command:
coolpup.py sub.LACZ.10kb.cool sub.unique.LACZ.loops.bedpe --n_proc 24 --outname slcool.v.slloops.txt

And it produced this error:
Traceback (most recent call last):
  File "/usr/local/bin/coolpup.py", line 5, in <module>
    from coolpuppy.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/coolpuppy/__init__.py", line 1, in <module>
    from .coolpup import *
  File "/usr/local/lib/python3.8/dist-packages/coolpuppy/coolpup.py", line 14, in <module>
    from cooltools import numutils, snipping
ImportError: cannot import name 'snipping' from 'cooltools' (/usr/local/lib/python3.8/dist-packages/cooltools/__init__.py)

I checked the cooltools API and it does have snipping.py in the directory. Wondering if you've seen this issue before?

**Comment by Phlya** [comment]
Sorry, forgot to reply to your question.
This is something about coolpuppy and cooltools versions, can you make sure you are using the latest released version of cooltools and the latest coolpuppy from the master branch?
