### ISSUE TITLE
coolpup.py snipping from cooltools error

### ISSUE THREAD

**Issue by yloemie** [open2c/coolpuppy#59]
Hi,
I get this error when I tried to use coolpup.py 

from cooltools import numutils, snipping
ImportError: cannot import name 'snipping' from 'cooltools'

cooltools, version 0.5.1

Did you see this already?

Thanks,

Yann

**Comment by Phlya** [comment]
Hi, please update coolpuppy to the latest version from the master branch to work with recent cooltools. Note we are preparing some major updates for the next release, so check the latest docs, there might be small differences depending on how you were using coolpuppy previously.

**Comment by yloemie** [comment]
Hi,

thanks for the quick answer. So yes I didn't have the error after updating. Now when I try to run coolpup.py I have this : 
`  File "/home/yloemie/miniconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/yloemie/miniconda3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 496, in main
    CC = CoordCreator(
TypeError: __init__() got an unexpected keyword argument 'anchor'
`

Maybe I need to redo my cool files (my files were generated with cooler-0.8.2).

Best,

Yann

**Comment by Phlya** [comment]
@efriman fix it now, should work!

**Comment by yloemie** [comment]
Yes it works, many thanks !

**Comment by Phlya** [comment]
Great!
