### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '.\n'

### ISSUE THREAD

**Issue by odovgusha** [open2c/coolpuppy#72]
coolpup.py $FOLDER/file.cool --outname $FOLDER/file.cool_out $FOLDER/encode_chipseq.bed
plotpup.py $FOLDER/file.cool_out  --output $FOLDER/test.png

and get 
Traceback (most recent call last):
  File "/usr/users/odovgus1/miniconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/usr/users/odovgus1/miniconda3/lib/python3.7/site-packages/coolpuppy/__main__.py", line 428, in main
    CC.process()
  File "/usr/users/odovgus1/miniconda3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 696, in process
    self.bases, self.kind = self.auto_read_bed(self.baselist)
  File "/usr/users/odovgus1/miniconda3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 383, in auto_read_bed
    int(row1[5]),
ValueError: invalid literal for int() with base 10: '.\n'
Traceback (most recent call last):

Could you suggest a reason for it?

**Comment by Phlya** [comment]
There is something wrong with your .bed file, looks like it contains ".\n" instead of one of the coordinates.

**Comment by odovgusha** [comment]
Sorry for the late reply 

Here is the bed file I am trying to use. I tried to look for odd "\n" but did not find any.
it has this structure.
Could you share the link to some toy chip_seq dataset that should work?
8	98946600	98946874	iPSC_RING1B_ChIP_peak_1619	49	.
8	98948910	98949129	iPSC_RING1B_ChIP_peak_1620	44	.
8	98949462	98949741	iPSC_RING1B_ChIP_peak_1621	29	.
8	98950388	98951290	iPSC_RING1B_ChIP_peak_1622	72	.
8	98951442	98951708	iPSC_RING1B_ChIP_peak_1623	36	.

[PRC2_encode_chipseq.zip](https://github.com/open2c/coolpuppy/files/8877685/PRC2_encode_chipseq.zip)

**Comment by Phlya** [comment]
OK! I think you are using an old version, and indeed there was an issue like that - to be more precise, if there were 6 columns in the file, it assumed that it was bedpe, not bed, hence it tried to convert your name/score/strand to coordinates and failed.
