### ISSUE TITLE
Study the correlation scaled pile up (aggregated) plot of TADs with box plot of TADs strength 

### ISSUE THREAD

**Issue by sachingadakh** [open2c/coolpuppy#85]
![cranegamhic](https://user-images.githubusercontent.com/44431816/184106590-072e4e9a-0716-49ad-9e21-e4ce7fff84b3.png)

 The strength of TADs correlates with self-interaction within TADs. In this figure, I observe HiC TADs seem to be better insulated and far more self-interacting compared to GAM TADs. My goal is to see whether a box plot comparing the TAD strength of HiC and GAM also shows the same thing i.e whether increased self-interaction showcased on the pile-up plot, also correlates with increased strength on the box plot or not. For reference regarding my goal (https://www.biorxiv.org/content/10.1101/523712v1.full.pdf   (fig1 f,j))

I want to know how to calculate the TAD strength score, is there any tool or already written code which could be available? I read the process mentioned in your paper (Flyamer et al., 2017), but didn't understand it well. 
Thank you

**Comment by Phlya** [comment]
How exactly would you define TAD strength score? There are different definitions in the literature, so before we try to write a solution for you, could you please let us know exactly what you want?

**Comment by sachingadakh** [comment]
Hello,
Thank you for responding. Sorry I couldn't reply earlier as I was on leave due to a health issue. Your question has put me into introspecting about How I am defining TAD strength or domain score. I read some literature and found out that principally it's called domain score and it can be calculated as intraTAD/(intraTAD+interTAD). The input would require the dumped contact matrix from the cool file and TAD file. 
reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4858530/

**Comment by efriman** [comment]
Hi,

Here is one suggestion of how to do this: https://gist.github.com/efriman/354a7edef41be40b21d201c7c9844fc9

I am using these settings:
rescale_flank=1
rescale=True
rescale_size=3
store_stripes=True

This will rescale your TADs and two neighbouring regions to one pixel each and store them individually as "stripes"", which you can then use to derive the value. In this example I am using non-normalised values (i.e. not normalised to expected or shifted controls), so if you do this just make sure the expected is not masked at the diagonal.

You need to update coolpup.py to the latest github release for this to work. Let us know if you manage!

**Comment by sachingadakh** [comment]
Hello Elias,
   Thank you for creating the solution. I will go through it and let you know how I am managing it.
Sachin

**Comment by Phlya** [comment]
Here is another solution, that also requires you to update coolpuppy to the latest version (again). It is in the main docs as an example of some advanced techniques, hope it helps!
https://coolpuppy.readthedocs.io/en/latest/Examples/TAD_score.html

**Comment by sachingadakh** [comment]
Thank you for this solution as well. I will try this one too and keep you in the loop with possible development with my data.

**Comment by Phlya** [comment]
Hi, did either solution work for you?

**Comment by sachingadakh** [comment]
> Hi, did either solution work for you?

Hello Phyla,
   I am still working on it. I started with the first solution; the updated coolpup took quite a while to get installed, and I finally had to create a new specific conda environment. Then sever at my workplace took almost a week to produce output with suggested parameters such as  : 
rescale_flank=1
rescale=True
rescale_size=3
store_stripes=True , since many other jobs were running on the server. 

Sooner I realized I might have to shift to Jupyter-notebook; I am now trying to install Jupyter-notebook on the server. 
If I face any issues, I will immediately let you know. Thank you

**Comment by sachingadakh** [comment]
Update:
Hello Phlya and Elias,
    So I got the output with first solution for HiC data. Thank you very much. Now for comparison, I would be repeating the same for my GAM data. I will keep you updated.

**Comment by sachingadakh** [comment]
Hello Elias,
  Your solution worked perfectly on HiC data, while it is throwing error for GAM data:
ValueError: No column 'bins/weight'found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.

I am aware that such error would occur while running GAM matrix because this matrix data doesn't weight column,  but coolpuppy for pileup used to take care of it with "--clr_weight_name ""  " parameter and I used to get pileup output for GAM data

Would there be possibility to allocate such parameter in your TAD_score code. Thank you

**Comment by Phlya** [comment]
add `clr_weight_name=False` when creating the PileUpper

**Comment by sachingadakh** [comment]
Hello Phyla and Elias,
 While rescaling the TADs on the GAM matrix, the heatmap is not showing the scaled TADs but turning totally black. I am aware the clr_weight_name =False, but the same parameter and data I used while rescaled pile up analysis(coolpup.py and plotpup.py)  and I did get good results of pileup plot using coolpuppy.

I am sharing the rescale output with you here :
![gam_tadstrength_issue](https://user-images.githubusercontent.com/44431816/188128884-68c944d9-f755-40ff-afe5-33f9c3a8b811.png)

**Comment by Phlya** [comment]
Try increasing vmax when plotting

**Comment by sachingadakh** [comment]
Thank you it improved. 
I am still figuring out the null TAD score for chr21 and chr22 while rescaling on the GAM matrix. I shall get back to you on that once I explore the raw data.
Thank you

**Comment by sachingadakh** [comment]
Hello Phlya and Elias,
  Thank you very much for your solutions. So far the first solution worked for us. We may attempt a second solution but as of now, we are happy with what we got. I am closing this issue. 
Thank you again.
Sachin
