### ISSUE TITLE
Recreating figure: And here is a real example of CTCF-associated loops in ES cells:

### ISSUE THREAD

**Issue by mattbramble** [open2c/coolpuppy#86]
Greetings, I've created a .clpy file, and I'm simply trying to recreate the figure stated in the heading:

"And here is a real example of CTCF-associated loops in ES cells"

on your walkthrough page.

I am unable to do this, although it seems like it should be a simple command.  
I've tried various heatmap methods, but none seem to work properly.
Thanks for any help.

**Comment by Phlya** [comment]
Please describe what exactly you tried, and what version of the tool you are using.

**Comment by mattbramble** [comment]
Ah, thanks, I just got it to work using the walkthrough CLI page, which has the relevant examples.
The following worked:
plotpup.py --output plot_out.png --input input.clpy

**Comment by mattbramble** [comment]
I am, however, still wondering how to define the range of interaction distances that a heatmap will cover.  For example, I need to include interactions of up to 800 kb.  The output shows a range of perhaps 200 kb around the central peaks, assuming the squares that I see correspond to the set resolution of 5 kb of the input cooler file.

**Comment by Phlya** [comment]
Great, glad you figured it out!

To pileup larger areas, you need to set the --flank argument.

**Comment by mattbramble** [comment]
Thanks for the help, Ilya.
