### ISSUE TITLE
[plotpup.py] How to draw multiple plots at once?

### ISSUE THREAD

**Issue by Soh-hyon** [open2c/coolpuppy#90]
Hi,

I want to draw multiple plots at once. I put 6 output files from coolpuppy under `--input_pups` parameter, but it seems like this is not the right way to draw multiple plots at once.

I also wanted to know the difference between **`cols` and `col_order`** or **`rows` and `row_order`**. If I want to use 3 columns with the names, "uniq_veh", "shared", and "uniq_treatment", how can I do?

The followings are my command line and errors.

**plotpup.py --input_pups veh_matrix.vs.uniq_veh_loops.txt veh_matrix.vs.shared_loops.txt veh_matrix.vs.uniq_AU15330_loops.txt AU15330_matrix.vs.uniq_veh_loops.txt AU15330_matrix.vs.shared_loops.txt AU15330_matrix.vs.uniq_AU15330_loops.txt --row_order veh,AU-15330 --col_order uniq_veh,shared,uniq_AU-15330 --vmin 1 --vmax 100 --output loops.png**

/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/coolpuppy/coolpup.py:314: RuntimeWarning: Mean of empty slice
  return np.nanmean(amap[c - n // 2 : c + n // 2 + 1, c - n // 2 : c + n // 2 + 1])
Traceback (most recent call last):
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/plotpuppy/CLI.py", line 343, in main
    fg = make_heatmap_grid(
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 528, in make_heatmap_grid
    fg.map(
  File "/home/nepi/anaconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 710, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/home/nepi/anaconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 806, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 111, in add_heatmap
    raise ValueError(
ValueError: Multiple pileups for one of the conditions, ensure unique correspondence for each col/row combination

**Comment by Phlya** [comment]
Are your files actually .txt? I.e. are you using the released version or the latest version from github?

Anyway, you need to "map" some annotation of the pileups across the rows and columns. E.g. like here https://coolpuppy.readthedocs.io/en/latest/Examples/Walkthrough_CLI.html#by-distance-pileups
So "rows" specifies what to map across the rows of a grid of heatmaps, and "row_order" lets you specify in what order to plot them, if you want. It all mimics the API of seaborn, by the way.

If you just want multiple plots, you can use "cool_path" or "features", depending on whether you are comparing different Hi-C datasets, or different regions.

**Comment by Soh-hyon** [comment]
Yes, I installed the latest version from github. The six inputs are the results of coolpup.py and they're binary files.

Actually, I'm following Dovetail's HiChIP processing workflow, but they wrote the command line using the older version of plotpup.py

Please see 4.2 Plot aggregate contacts with plotpup in above link.
https://hichip.readthedocs.io/en/latest/hichip_compare.html#apa-analysis-to-confirm-loop-analysis
![image](https://user-images.githubusercontent.com/111338605/190566038-e679ff51-dc8a-4ea2-8d6b-d16f2be4c834.png)

The six plots are not indicating different regions nor totally different datasets. There are two conditions (Sample A & B) and loops are classified into unique loops or shared loops. It's exactly what I want to draw.

If it doesn't bother you too much, can you convert the command line in 4.2 based on the latest version of plotpup.py?

**Comment by Phlya** [comment]
I see! I didn't know they used coolpuppy in their manual, that's nice.
To be honest, for you it might be easiest to just install the older version that is available on PyPI and use the exact commands they provide. In this case the new version doesn't provide any benefit.

**Comment by Soh-hyon** [comment]
Which older version has the same argument as Dovetail described?

**Comment by Phlya** [comment]
Should be the one available from PyPI, the latest release.

**Comment by Soh-hyon** [comment]
Since the older version is not compatible with higher python version, I made a virtual environment and installed python3.6, then installed coolpuppy 0.9.5 and all the requirements.

Fortunately, the optional arguments Dovetail used were included in 0.9.5, so I thought everything was okay! However, I got the following errors. How can I solve this problem?

```
(py36) nepi_SH@nepi:/media/nepi/nepi_18TB_V2/data_2022/Soh-hyon/HiChIP/Practice_Nature2022/H3K27ac/APA$ plotpup.py veh_matrix.vs.uniq_veh_     loops.txt veh_matrix.vs.shared_loops.txt veh_matrix.vs.uniq_AU15330_loops.txt AU15330_matrix.vs.uniq_AU15330_loops.txt AU15330_matrix.vs.s     hared_loops.txt AU15330_matrix.vs.uniq_veh_loops.txt --row_names veh,AU-15330 --col_names unique_veh,shared,unique_AU-15330 --n_cols 3 --v     min 1 --vmax 100 --output loops.png
Traceback (most recent call last):
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.6/site-packages/coolpuppy/__plotpuppy_main__.py", line 147, in main
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.6/site-packages/coolpuppy/__plotpuppy_main__.py", line 147, in <listcomp     >
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.6/site-packages/coolpuppy/coolpup.py", line 54, in load_array_with_heade     r
    read_data = f.read()
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.conda/envs/py36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

```

**Comment by Soh-hyon** [comment]
I solved the above issue! You don't have to worry about it.
I only used the older version of plotpup.py and the input files were from the latest version of coolpup.py. The problem was solved after I made the input files from the older version of coolpup.py.

**Comment by Phlya** [comment]
Great to hear! Indeed, output file formats are completely different and would cause such an error.

**Comment by Soh-hyon** [comment]
There's no running error while using coolpup.py and plotpup.py, but there's nothing drawn in the output plot file.
![image](https://user-images.githubusercontent.com/111338605/194121458-f8eb5b11-f57f-4127-bacb-d7660ef77211.png)
Even though I changed the parameters such as `--vmax`, there's still nothing in the plot.
Then, I checked the output file of coolpup.py and found that all the value was zero. (See below)
![image](https://user-images.githubusercontent.com/111338605/194121942-1830f135-2edf-4cd3-8138-4defb1355d21.png)

When making the input file for plotpup.py (=while running coolpup.py), there was a runtime warning about an invalid value. I think this warning is related to all zero weights in the file.
```
coolpup.py ../H3K27ac_veh_matrix_5kb.cool ../FitHiChIP_result_shortcut/u  nique.veh.loops.bedpe --unbalanced --n_proc 24 --outname veh_matrix.vs.uniq_veh_loops.txt
Namespace(anchor=None, baselist='../FitHiChIP_result_shortcut/unique.veh.loops.bedpe', bed2=None, bed2_ordered=True, by_window=False, coolfile='../H3K27ac_veh_matrix_5kb.cool',   coverage_norm=False, excl_chrs='chrY,chrM', expected=None, ignore_diags=2, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist  =None, minshift=100000, minsize=None, n_proc=24, nshifts=10, outdir='.', outname='veh_matrix.vs.uniq_veh_loops.txt', pad=100, post_mortem=False, rescale=False, rescale_pad=1.0,   rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=True, weight_name='weight')
Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Nothing to sum up in chromosome chr12
chr12: 0
chr15: 2
chr13: 2
chr20: 1
chr17: 3
chr8: 3
chr16: 1
chr9: 3
chr11: 3
chr5: 1
chr3: 3
chr6: 3
chr1: 3
Total number of piled up windows: 28
Nothing to sum up in chromosome chr12
chr12: 0
chr20: 10
chr13: 20
chr17: 30
chr11: 30
chr9: 30
chr8: 30
chr16: 10
chr6: 30
chr15: 20
chr5: 10
chr3: 30
chr1: 30
Total number of piled up control windows: 280
/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.6/site-packages/coolpuppy/coolpup.py:1191: **RuntimeWarning: invalid value encountered in true_divide**
  loop /= ctrl
Saved output to /media/nepi/nepi_18TB_V2/data_2022/Soh-hyon/HiChIP/Practice_Nature2022/H3K27ac/APA/veh_matrix.vs.uniq_veh_loops.txt
```

Do you know why this happened?

**Comment by Phlya** [comment]
Looks like you have way too few loops...

**Comment by rikrdo89** [comment]
Did you ever figure out  the parameter for plotpup.py when having multiple input files? I know I use used `--row` but not sure what "category" should I use to plot the individual clpy files.

**Comment by Phlya** [comment]
@rikrdo89 it depends on what you are trying to achieve. For example, you can use `--row cooler` to use the name of the cooler files you used to create different pileups...
To see what is possible with your files, since it depends on how the files were produced, you can load them in python using e.g. this function https://coolpuppy.readthedocs.io/en/latest/modules.html#coolpuppy.lib.io.load_pileup_df and check what columns are available in the dataframe.

**Comment by rikrdo89** [comment]
Thanks a lot! I actually inspected the pandas dataframe and realized that the column with the different files is `cooler`; thanks for being so responsive!

The final flags I used to plot multiple files (in addition to multiple categories) is `--cols category1  --rows cooler`. Works like a charm, thanks for the awesome tool.
