### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by BioEpi** [open2c/coolpuppy#97]
hello,
   when I used `pip install https://github.com/open2c/coolpuppy/archive/master.zip`to install coolpuppy, I got this error:
**ModuleNotFoundError: No module named 'coolpuppy.lib'**, when I run `coolpup.py -h`

when I try this pip install https://github.com/open2c/coolpuppy/archive/refs/heads/master.zip, I still encounter the same error.

Do you know how to fix this error?

**Comment by efriman** [comment]
Hi,

Did you install Cython first?

https://pypi.org/project/Cython/

**Comment by BioEpi** [comment]
Thanks both of you. yes, I previously installed the coolpup.py via pip install cool puppy.
So do I need to uninstall the coolpup.py via pip uninstall coolpuppy firstly, and then reinstall coolpuppy?

**Comment by Phlya** [comment]
If you use the command I provided it will for sure reinstall.

**Comment by BioEpi** [comment]
when I ran `python3 -m pip install --force-reinstall --update --no-cache-dir --no-deps https://github.com/open2c/coolpuppy/archive/refs/heads/master.zip`, I got this error "**no such option: --update**"

**Comment by BioEpi** [comment]
another question: can I run `cooltools expected-cis` to calculate the expected contact frequency? Because cooltools does not have `cooltools compute-expected` command.

**Comment by BioEpi** [comment]
> Hi,
> 
> Did you install Cython first?
> 
> https://pypi.org/project/Cython/

yes, I did

**Comment by Phlya** [comment]
whoops sorry, upgrade is the right option!

**Comment by BioEpi** [comment]
> whoops sorry, upgrade is the right option!

it is ok.

when I try to plot via plotpup.py, I got this error
Traceback (most recent call last):
File "/data/anaconda3/bin/plotpup.py", line 8, in
sys.exit(main())
File "/data/anaconda3/lib/python3.8/site-packages/plotpuppy/CLI.py", line 297, in main
numutils.get_score,
AttributeError: module 'coolpuppy.lib.numutils' has no attribute 'get_score'

another question: can I run cooltools expected-cis to calculate the expected contact frequency? Because cooltools does not have cooltools compute-expected command.

**Comment by Phlya** [comment]
Error should be fixed now!

Yes, `expected-cis` is the new name for the `compute expected --cis` command

**Comment by BioEpi** [comment]
it works now. thanks.

**Comment by BioEpi** [comment]
another question:
how to show the tricks in the y-axis, now the x-asix has the tricks.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/12387462/192291412-4e59a1ee-efbf-4f38-8cd0-ee8331f90d49.png">

**Comment by efriman** [comment]
Yes it's only showing the x-axis tick values, as they are the same anyway. This is because the y axis ones tend to bleed into the row name. If you make another issue with a feature request for this we can have a look in the future. Or you can make your own plot using matplotlib imshow (https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html) if you only have one pileup
