### ISSUE TITLE
plot TAD error

### ISSUE THREAD

**Issue by BioEpi** [open2c/coolpuppy#98]
I called TADs using matrix2insulation.
when I used coolpup.py my_hic_data.cool my_domains.bed --rescale --local to plot TADs, I got this error:
ValueError: **Maximum value is less than 1.0, can't plot using symmetrical scale**.
Do you know which argument can be used to fix this issue?

**Comment by efriman** [comment]
With plotpup.py you can add the argument --not_symmetric

**Comment by BioEpi** [comment]
got it.
what is the input file for this figure? 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/12387462/192360283-da1e00c9-b0c0-466e-bb8b-c596e7431540.png">
When I used boundary regions (10kb around the TAD anchors) to run coolpup.py, I got a very weird figure.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/12387462/192360625-51690fa7-34bd-438a-b84d-1786373ecd0c.png">
do you think the input file I used is correct?
Best,

**Comment by Phlya** [comment]
You need higher resolution and/or bigger flank.

**Comment by BioEpi** [comment]
do you mean the cool file? or both cool file and TAD boundary?

**Comment by Phlya** [comment]
I didn't quite get what you did exactly, but to get a similar figure you need 100 kbp flank with high resolution of the cooler, the figure above looks like 1 kbp resolution.

**Comment by Phlya** [comment]
Note that you can also use e.g. 10 kb resolution and still get a nice figure, maybe 300 kb flank would look nicer though (see examples in docs, there is a very similar figure there with exact code to reproduce it).
